"""Bootstrap script for the legal monitoring pipeline.

Orchestrates initial data load:
  1. Register all 67+ sources in legal_source_state
  2. Import tourism decree JSONs
  3. Fetch current content from active sources, compute initial hashes
  4. Run keyword filter on all current bulletin entries
  5. Classify matches via local Ollama
  6. Export as SQL dump

Usage:
    python -m legal.bootstrap --llm-backend ollama
    python -m legal.bootstrap --llm-backend ollama --output data/legal/bootstrap_results.sql
    python -m legal.bootstrap --skip-fetch   # Only register sources + seed decrees
"""

import argparse
import logging
import os
import sys

from utils import get_db_connection, setup_logging

logger = setup_logging("legal-bootstrap")


def register_all_sources() -> int:
    logger.info("=== Step 1: Registering all sources ===")
    count = 0

    from watchers.boe_watcher import ensure_source_registered as boe_reg
    boe_reg()
    count += 1

    if os.environ.get("AEMET_API_KEY"):
        from watchers.aemet_watcher import ensure_source_registered as aemet_reg
        aemet_reg()
        count += 1

    from watchers.rss_configs import RSS_SOURCES
    from watchers.rss_watcher import ensure_sources_registered as rss_reg
    rss_reg(RSS_SOURCES)
    count += len(RSS_SOURCES)

    from watchers.html_configs import HTML_SOURCES
    from watchers.html_scraper import ensure_sources_registered as html_reg
    html_reg(HTML_SOURCES)
    count += len(HTML_SOURCES)

    from watchers.bop_configs import BOP_CONFIGS
    from watchers.bop_scraper import ensure_sources_registered as bop_reg
    bop_reg(BOP_CONFIGS)
    count += len(BOP_CONFIGS)

    logger.info("Registered %d sources", count)
    return count


def seed_decrees() -> int:
    logger.info("=== Step 2: Seeding tourism decrees ===")
    from legal.decrees_seed import seed
    seed(dry_run=False)

    conn = get_db_connection()
    try:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT COUNT(*) FROM legal_documents WHERE restriction_type = 'tourism_decree'"
            )
            count = cur.fetchone()[0]
    finally:
        conn.close()

    logger.info("Seeded %d tourism decrees", count)
    return count


def fetch_initial_content() -> dict:
    logger.info("=== Step 3: Fetching current content ===")
    results = {"rss": 0, "boe": 0, "aemet": 0, "html": 0}

    from watchers.boe_watcher import BoeWatcher
    try:
        boe = BoeWatcher()
        results["boe"] = boe.check_and_store()
        logger.info("BOE: %d documents", results["boe"])
    except Exception:
        logger.exception("BOE fetch failed")

    if os.environ.get("AEMET_API_KEY"):
        from watchers.aemet_watcher import AemetWatcher
        try:
            aemet = AemetWatcher()
            results["aemet"] = aemet.check_and_store()
            logger.info("AEMET: %d fire alerts", results["aemet"])
        except Exception:
            logger.exception("AEMET fetch failed")

    from watchers.rss_configs import RSS_SOURCES
    from watchers.rss_watcher import RssWatcher
    rss = RssWatcher()
    for config in RSS_SOURCES:
        try:
            count = rss.check_and_store(config)
            results["rss"] += count
        except Exception:
            logger.exception("RSS %s failed", config["source_id"])

    logger.info("Fetch results: %s", results)
    return results


def classify_pending(llm_backend: str, batch_size: int = 20) -> int:
    logger.info("=== Step 4: Classifying pending documents ===")
    from legal.classifier import LegalClassifier

    classifier = LegalClassifier(llm_backend=llm_backend)
    total = 0

    while True:
        count = classifier.process_batch(limit=batch_size)
        total += count
        if count < batch_size:
            break
        logger.info("Classified %d so far...", total)

    logger.info("Total classified: %d", total)
    return total


def run_dedup() -> dict:
    logger.info("=== Step 5: Deduplication ===")
    from legal.dedup import LegalDedup
    dedup = LegalDedup()
    return dedup.run()


def export_sql(output_path: str) -> None:
    logger.info("=== Step 6: Exporting SQL ===")
    conn = get_db_connection()
    try:
        with conn.cursor() as cur:
            cur.execute("SELECT COUNT(*) FROM legal_source_state")
            source_count = cur.fetchone()[0]
            cur.execute("SELECT COUNT(*) FROM legal_documents WHERE status = 'active'")
            doc_count = cur.fetchone()[0]

        with open(output_path, "w", encoding="utf-8") as f:
            f.write("-- WildSpotter Legal Pipeline Bootstrap\n")
            f.write(f"-- Sources: {source_count}, Documents: {doc_count}\n")
            f.write("-- Generated by legal_bootstrap.py\n\n")
            f.write("BEGIN;\n\n")

            with conn.cursor() as cur:
                cur.execute("""
                    SELECT id, name, source_type, region, url, poll_interval_hours
                    FROM legal_source_state ORDER BY id
                """)
                f.write("-- Sources\n")
                for row in cur.fetchall():
                    vals = ", ".join(
                        f"'{v}'" if isinstance(v, str) else str(v) if v is not None else "NULL"
                        for v in row
                    )
                    f.write(
                        f"INSERT INTO legal_source_state (id, name, source_type, region, url, poll_interval_hours) "
                        f"VALUES ({vals}) ON CONFLICT (id) DO NOTHING;\n"
                    )

                f.write("\n-- Documents\n")
                cur.execute("""
                    SELECT id, source_id, title, restriction_type, affected_ccaa,
                           affected_province, affected_municipality, confidence_tier,
                           effective_from, effective_until, content_hash, status
                    FROM legal_documents
                    WHERE status = 'active'
                    ORDER BY created_at
                """)
                for row in cur.fetchall():
                    vals = ", ".join(
                        f"'{str(v).replace(chr(39), chr(39)+chr(39))}'"
                        if isinstance(v, str)
                        else f"'{v.isoformat()}'" if hasattr(v, "isoformat")
                        else str(v) if v is not None
                        else "NULL"
                        for v in row
                    )
                    f.write(
                        f"INSERT INTO legal_documents (id, source_id, title, restriction_type, "
                        f"affected_ccaa, affected_province, affected_municipality, confidence_tier, "
                        f"effective_from, effective_until, content_hash, status) "
                        f"VALUES ({vals}) ON CONFLICT (id) DO NOTHING;\n"
                    )

            f.write("\nCOMMIT;\n")

        logger.info("Exported to %s (%d sources, %d docs)", output_path, source_count, doc_count)
    finally:
        conn.close()


def main() -> None:
    parser = argparse.ArgumentParser(description="Legal pipeline bootstrap")
    parser.add_argument("--llm-backend", default="ollama", choices=["ollama", "haiku"])
    parser.add_argument("--output", default="data/legal/bootstrap_results.sql")
    parser.add_argument("--skip-fetch", action="store_true", help="Skip fetching from sources")
    parser.add_argument("--skip-classify", action="store_true", help="Skip LLM classification")
    parser.add_argument("--batch-size", type=int, default=20)
    args = parser.parse_args()

    logger.info("Starting legal pipeline bootstrap (llm=%s)", args.llm_backend)

    register_all_sources()
    seed_decrees()

    if not args.skip_fetch:
        fetch_initial_content()
    else:
        logger.info("Skipping content fetch")

    if not args.skip_classify:
        classify_pending(args.llm_backend, args.batch_size)
    else:
        logger.info("Skipping classification")

    run_dedup()

    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    export_sql(args.output)

    conn = get_db_connection()
    try:
        with conn.cursor() as cur:
            cur.execute("SELECT COUNT(*) FROM legal_source_state")
            sources = cur.fetchone()[0]
            cur.execute("SELECT COUNT(*) FROM legal_documents WHERE status = 'active'")
            docs = cur.fetchone()[0]
            cur.execute(
                "SELECT confidence_tier, COUNT(*) FROM legal_documents "
                "WHERE status = 'active' GROUP BY confidence_tier"
            )
            tiers = {r[0]: r[1] for r in cur.fetchall()}
    finally:
        conn.close()

    logger.info("=" * 50)
    logger.info("BOOTSTRAP COMPLETE")
    logger.info("  Sources registered: %d", sources)
    logger.info("  Active documents: %d", docs)
    logger.info("  By tier: %s", tiers)
    logger.info("  Export: %s", args.output)
    logger.info("=" * 50)


if __name__ == "__main__":
    main()
