"""
Step 5: Train a lightweight ground-suitability classifier.

Trains a MobileNetV2-based binary classifier on labeled satellite tiles.
Exports to TFLite and ONNX for on-device inference in the app.

Input: labeled/ directory with ground_suitable/ and ground_unsuitable/ folders
       (generated by autolabeler.py, optionally corrected via reviewer.html)

Output: spot-classifier.tflite, spot-classifier.onnx

Usage:
    python train.py
    python train.py --epochs 20 --batch-size 16
"""

import argparse
import csv
import os
import shutil

import numpy as np

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

import tensorflow as tf
from PIL import Image

# Match the app's expected input (src/services/ai/preprocessing.ts)
IMG_SIZE = 256
LABELED_DIR = "labeled"
CORRECTED_CSV = "labels_corrected.csv"
MODEL_NAME = "spot-classifier"


def apply_corrections():
    """If a corrected CSV exists from the reviewer, re-sort images."""
    if not os.path.exists(CORRECTED_CSV):
        return

    print("Applying label corrections from reviewer...")
    with open(CORRECTED_CSV) as f:
        reader = csv.DictReader(f)
        corrections = [r for r in reader if r["corrected"] == "True"]

    if not corrections:
        print("  No corrections to apply.")
        return

    dataset_dir = "dataset_images"
    for row in corrections:
        fname = row["filename"]
        new_label = row["label"]

        # Find the image in dataset_images
        for subdir in ["positive", "negative"]:
            src = os.path.join(dataset_dir, subdir, fname)
            if os.path.exists(src):
                dst = os.path.join(LABELED_DIR, new_label, fname)
                # Remove from old label dir
                for label_dir in ["ground_suitable", "ground_unsuitable"]:
                    old = os.path.join(LABELED_DIR, label_dir, fname)
                    if os.path.exists(old) and old != dst:
                        os.remove(old)
                shutil.copy2(src, dst)
                break

    print(f"  Applied {len(corrections)} corrections.")


def deduplicate_labeled_dir():
    """Remove duplicate images from labeled/ by content hash."""
    import hashlib

    seen: set[str] = set()
    removed = 0
    for label_dir in ["ground_suitable", "ground_unsuitable"]:
        folder = os.path.join(LABELED_DIR, label_dir)
        if not os.path.isdir(folder):
            continue
        for fname in sorted(os.listdir(folder)):
            fpath = os.path.join(folder, fname)
            if not fname.lower().endswith((".jpg", ".jpeg", ".png")):
                continue
            with open(fpath, "rb") as f:
                h = hashlib.md5(f.read()).hexdigest()
            if h in seen:
                os.remove(fpath)
                removed += 1
            else:
                seen.add(h)

    if removed > 0:
        print(f"  Removed {removed} duplicate images from labeled/")


def load_dataset(batch_size: int) -> tuple:
    """Load images from labeled/ directory into tf.data.Datasets."""
    deduplicate_labeled_dir()

    suitable_dir = os.path.join(LABELED_DIR, "ground_suitable")
    unsuitable_dir = os.path.join(LABELED_DIR, "ground_unsuitable")

    if not os.path.isdir(suitable_dir) or not os.path.isdir(unsuitable_dir):
        raise FileNotFoundError(
            f"Missing {LABELED_DIR}/ground_suitable/ or ground_unsuitable/. "
            "Run autolabeler.py or smartlabeler.py first."
        )

    suitable_count = len([f for f in os.listdir(suitable_dir) if f.lower().endswith(('.jpg', '.jpeg', '.png'))])
    unsuitable_count = len([f for f in os.listdir(unsuitable_dir) if f.lower().endswith(('.jpg', '.jpeg', '.png'))])
    total = suitable_count + unsuitable_count
    print(f"Dataset: {suitable_count} suitable, {unsuitable_count} unsuitable ({total} total)")

    # Use Keras image loading with augmentation
    train_ds = tf.keras.utils.image_dataset_from_directory(
        LABELED_DIR,
        labels="inferred",
        label_mode="binary",
        class_names=["ground_unsuitable", "ground_suitable"],
        image_size=(IMG_SIZE, IMG_SIZE),
        batch_size=batch_size,
        validation_split=0.2,
        subset="training",
        seed=42,
    )

    val_ds = tf.keras.utils.image_dataset_from_directory(
        LABELED_DIR,
        labels="inferred",
        label_mode="binary",
        class_names=["ground_unsuitable", "ground_suitable"],
        image_size=(IMG_SIZE, IMG_SIZE),
        batch_size=batch_size,
        validation_split=0.2,
        subset="validation",
        seed=42,
    )

    # Normalize to [0, 1]
    normalize = tf.keras.layers.Rescaling(1.0 / 255)
    train_ds = train_ds.map(lambda x, y: (normalize(x), y))
    val_ds = val_ds.map(lambda x, y: (normalize(x), y))

    # Data augmentation for training
    augment = tf.keras.Sequential([
        tf.keras.layers.RandomFlip("horizontal_and_vertical"),
        tf.keras.layers.RandomRotation(0.2),
        tf.keras.layers.RandomBrightness(0.1),
        tf.keras.layers.RandomContrast(0.1),
    ])
    train_ds = train_ds.map(lambda x, y: (augment(x, training=True), y))

    # Performance optimization
    train_ds = train_ds.prefetch(tf.data.AUTOTUNE)
    val_ds = val_ds.prefetch(tf.data.AUTOTUNE)

    return train_ds, val_ds


def build_model() -> tf.keras.Model:
    """MobileNetV2-based binary classifier, optimized for small model size."""
    base = tf.keras.applications.MobileNetV2(
        input_shape=(IMG_SIZE, IMG_SIZE, 3),
        include_top=False,
        weights="imagenet",
    )

    # Freeze early layers, fine-tune the last 30
    for layer in base.layers[:-30]:
        layer.trainable = False

    model = tf.keras.Sequential([
        base,
        tf.keras.layers.GlobalAveragePooling2D(),
        tf.keras.layers.Dropout(0.3),
        tf.keras.layers.Dense(64, activation="relu"),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(1, activation="sigmoid"),
    ])

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
        loss="binary_crossentropy",
        metrics=["accuracy", tf.keras.metrics.AUC(name="auc")],
    )

    return model


def export_tflite(model: tf.keras.Model):
    """Export to TFLite with int8 quantization for smallest size."""
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]

    # Dynamic range quantization (no calibration data needed)
    tflite_model = converter.convert()
    path = f"{MODEL_NAME}.tflite"
    with open(path, "wb") as f:
        f.write(tflite_model)
    size_mb = os.path.getsize(path) / (1024 * 1024)
    print(f"Exported {path} ({size_mb:.1f} MB)")


def export_tfjs(model: tf.keras.Model):
    """Export to TensorFlow.js format for in-browser inference."""
    try:
        import tensorflowjs as tfjs

        tfjs_dir = os.path.join("..", "public", "models", MODEL_NAME)
        os.makedirs(tfjs_dir, exist_ok=True)
        tfjs.converters.save_keras_model(model, tfjs_dir)
        print(f"Exported TF.js model to {tfjs_dir}/")
    except ImportError:
        print("Skipping TF.js export (tensorflowjs not installed: pip install tensorflowjs)")
    except Exception as e:
        print(f"TF.js export failed: {e}")


def train(epochs: int, batch_size: int):
    apply_corrections()

    train_ds, val_ds = load_dataset(batch_size)

    # Compute class weights from labeled/ directory
    suitable_count = len([f for f in os.listdir(os.path.join(LABELED_DIR, "ground_suitable"))
                         if f.lower().endswith(('.jpg', '.jpeg', '.png'))])
    unsuitable_count = len([f for f in os.listdir(os.path.join(LABELED_DIR, "ground_unsuitable"))
                           if f.lower().endswith(('.jpg', '.jpeg', '.png'))])
    total = suitable_count + unsuitable_count
    class_weight = {
        0: total / (2 * unsuitable_count) if unsuitable_count > 0 else 1.0,
        1: total / (2 * suitable_count) if suitable_count > 0 else 1.0,
    }
    print(f"Class weights: unsuitable={class_weight[0]:.2f}, suitable={class_weight[1]:.2f}")

    model = build_model()
    model.summary()

    callbacks = [
        tf.keras.callbacks.EarlyStopping(
            monitor="val_auc", patience=5, mode="max", restore_best_weights=True
        ),
        tf.keras.callbacks.ReduceLROnPlateau(
            monitor="val_loss", factor=0.5, patience=3, min_lr=1e-6
        ),
    ]

    print(f"\nTraining for up to {epochs} epochs...")
    history = model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=epochs,
        callbacks=callbacks,
        class_weight=class_weight,
    )

    # Evaluate
    val_loss, val_acc, val_auc = model.evaluate(val_ds)
    print(f"\nValidation — Loss: {val_loss:.4f}, Accuracy: {val_acc:.4f}, AUC: {val_auc:.4f}")

    # Export
    print("\nExporting models...")
    export_tflite(model)
    export_tfjs(model)

    print(f"\nDone. TFLite model: {MODEL_NAME}.tflite")
    print("TF.js model: ../public/models/spot-classifier/ (ready for Expo Web)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train WildSpotter spot classifier")
    parser.add_argument("--epochs", type=int, default=15, help="Max training epochs")
    parser.add_argument("--batch-size", type=int, default=16, help="Batch size")
    args = parser.parse_args()
    train(args.epochs, args.batch_size)
